# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.simpledeckserver import (
    DeleteItem_Responses,
    MoveItem_Responses,
    PutItem_Responses,
    SimpleDeckServerBase,
)

if TYPE_CHECKING:
    from ..server import Server

import requests
class SimpleDeckServerImpl(SimpleDeckServerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def get_StartDate(self, *, metadata: MetadataDict) -> str:
        raise NotImplementedError  # TODO

    def PutItem(self, Spot: str, UUID: str, Type: str, *, metadata: MetadataDict) -> PutItem_Responses:
        url = "http://localhost:8000/put_item/{}".format(Spot)
        payload = {
            "uuid": UUID,
            "type": Type
        }
        response = requests.put(url, json = payload)
        print("Status Code: {}".format(response.status_code))
        if response.status_code == 200:
            return True
        else:
            return False
        raise NotImplementedError  # TODO

    def DeleteItem(self, Spot: str, *, metadata: MetadataDict) -> DeleteItem_Responses:

        raise NotImplementedError  # TODO

    def MoveItem(self, From: str, To: str, *, metadata: MetadataDict) -> MoveItem_Responses:
        raise NotImplementedError  # TODO
